[package]
name = "mkit-gpui-kit-coexistence"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
gpui_pre.workspace = true
gpui-kit = "=0.6.4"
mkit.workspace = true

[dev-dependencies]
gpui-kit = { version = "=0.6.4", features = ["test-support"] }
