import { ui } from '../ui/icons'
import type { DemoMap } from '../ui/types'

const calendar = (selected = 15) => {
  const days = ['M', 'T', 'W', 'T', 'F', 'S', 'S']
  const dates = [null, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, null, null, null, null, null, null, null, null, null, null, null, null]
  return `<div class="e7-calendar" role="grid" aria-label="April 2024">
    <div class="e7-calendar__head"><button class="ui-btn ui-btn--ghost ui-btn--icon ui-btn--sm" aria-label="Previous month">${ui('chevron-left')}</button><b>April 2024</b><button class="ui-btn ui-btn--ghost ui-btn--icon ui-btn--sm" aria-label="Next month">${ui('chevron-right')}</button></div>
    <div class="e7-calendar__grid">${days.map((d) => `<span class="e7-calendar__weekday">${d}</span>`).join('')}${dates.map((d) => d ? `<button class="e7-calendar__day${d === selected ? ' is-selected' : ''}" role="gridcell" aria-selected="${d === selected}">${d}</button>` : '<span></span>').join('')}</div>
  </div>`
}

const suggestion = (text: string, active = false, meta = '') => `<div class="ui-menu__item${active ? ' is-active' : ''}" role="option" aria-selected="${active}">${text}<span class="ui-menu__shortcut">${meta}</span></div>`

export const e7Expansion: DemoMap = {
  calendar: { html: `<div class="ui-col" style="gap:8px"><span class="ui-label">Calendar</span><span class="ui-description">single</span>${calendar()}</div>`, align: 'start' },
  'date-picker': { html: `<div class="ui-col" style="gap:8px;width:240px"><label class="ui-label" for="e7-date">Date</label><div class="ui-input-wrap"><input id="e7-date" class="ui-input" value="2024-04-15" aria-label="Date, April 15, 2024"><button class="e7-date-trigger" aria-label="Open calendar">${ui('calendar')}</button></div><div class="ui-popover e7-date-pop">${calendar()}</div></div>`, align: 'start' },
  disclosure: { html: `<div class="ui-col" style="width:min(420px,100%);gap:8px"><span class="ui-label">Disclosure</span><section class="ui-card e7-disclosure"><button class="e7-disclosure__trigger" aria-expanded="true"><span>Advanced settings</span>${ui('chevron-down')}</button><div class="e7-disclosure__body" id="advanced-settings">Additional controls are available.</div></section></div>`, align: 'start' },
  toolbar: { html: `<div class="ui-col" style="gap:10px"><span class="ui-label">Horizontal toolbar</span><div class="e7-toolbar" role="toolbar" aria-label="Text editing"><button class="ui-btn ui-btn--outline ui-btn--sm">Undo</button><button class="ui-btn ui-btn--primary ui-btn--sm" aria-pressed="true">Left</button><button class="ui-btn ui-btn--outline ui-btn--sm">Center</button><button class="ui-btn ui-btn--outline ui-btn--sm">Right</button><button class="ui-btn ui-btn--primary ui-btn--sm" aria-pressed="true">Bold</button><button class="ui-btn ui-btn--outline ui-btn--sm">Share</button><button class="ui-btn ui-btn--outline ui-btn--sm" disabled>Archive</button></div></div>`, align: 'start' },
  'time-field': { html: `<div class="ui-col" style="gap:8px"><span class="ui-label">Time</span><div class="e7-time" role="group" aria-label="Time"><span tabindex="0" class="is-focused">09</span><i>:</i><span tabindex="0">35</span><i>:</i><span tabindex="0">12</span><span tabindex="0">AM</span></div></div>`, align: 'start' },
  'date-time-field': { html: `<div class="ui-col" style="gap:8px;width:270px"><span class="ui-label">Appointment</span><div class="ui-input-wrap"><input class="ui-input" value="2024-04-15 09:35 AM" aria-label="Appointment date and time"><button class="e7-date-trigger" aria-label="Open date picker">${ui('calendar')}</button></div><span class="ui-description">April 15, 2024 · 9:35 AM</span></div>`, align: 'start' },
  badge: { html: `<div class="ui-col" style="gap:10px"><span class="ui-label">Badges</span><div class="ui-row"><span class="ui-badge">Default</span><span class="ui-badge ui-badge--secondary">Secondary</span><span class="ui-badge ui-badge--outline">Outline</span><span class="ui-badge ui-badge--destructive">Error</span><span class="ui-badge e7-status-badge">● Success</span></div></div>`, align: 'start' },
  avatar: { html: `<div class="ui-col" style="gap:10px"><span class="ui-label">Avatar · initials</span><div class="ui-row" style="gap:12px"><span class="e7-avatar">JD</span><span class="e7-avatar e7-avatar--alt">MK</span><span class="e7-avatar e7-avatar--fallback" aria-label="User">${ui('user')}</span><span class="e7-avatar e7-avatar--small">AL</span></div></div>`, align: 'start' },
  'key-hint': { html: `<div class="ui-col" style="gap:10px"><span class="ui-label">Keyboard shortcuts</span><div class="ui-row"><kbd class="ui-kbd">⌘</kbd><kbd class="ui-kbd">K</kbd><span class="ui-muted">Open command menu</span></div><div class="ui-row"><kbd class="ui-kbd">⇧</kbd><kbd class="ui-kbd">⌘</kbd><kbd class="ui-kbd">P</kbd><span class="ui-muted">Search components</span></div></div>`, align: 'start' },
  link: { html: `<div class="ui-col" style="gap:10px"><span class="ui-label">Links</span><a class="e7-link" href="#link-preview">View documentation ${ui('chevron-right')}</a><a class="e7-link e7-link--muted" href="#external-preview">External resource ${ui('chevron-right')}</a></div>`, align: 'start' },
  'inline-alert': { html: `<div class="ui-col" style="width:min(440px,100%);gap:10px"><span class="ui-label">Inline alerts</span><div class="e7-alert" role="status">${ui('circle-check')}<div><b>Changes saved</b><p>Your project is up to date.</p></div></div><div class="e7-alert e7-alert--warning" role="alert">${ui('alert-triangle')}<div><b>Storage almost full</b><p>Free up space to keep syncing.</p></div></div></div>`, align: 'start' },
  'search-field': { html: `<div class="ui-col" style="gap:8px;width:280px"><label class="ui-label" for="e7-search">Search</label><div class="ui-input-wrap">${ui('search')}<input class="ui-input" id="e7-search" value="curve" aria-label="Search components"></div><div class="ui-popover ui-menu e7-search-results" role="listbox" aria-label="Suggestions">${suggestion('Curve editor', true, '↵')}${suggestion('Curve presets')}${suggestion('Curve points')}</div></div>`, align: 'start' },
  'status-bar': { html: `<div class="ui-col" style="gap:8px;width:min(560px,100%)"><span class="ui-label">Status bar · full</span><div class="e7-status-bar"><span>Document ready</span><span>All changes saved</span><button>Details</button><span class="e7-status-spacer"></span><span class="e7-zoom">−　100%　+</span><button>Undo</button><button>Export</button></div></div>`, align: 'start' },
  'tag-input': { html: `<div class="ui-col" style="gap:8px;width:300px"><label class="ui-label" for="e7-tags">Tags</label><div class="e7-tags" role="group" aria-label="Tags"><span class="ui-badge ui-badge--secondary">Design <button aria-label="Remove Design">${ui('x')}</button></span><span class="ui-badge ui-badge--secondary">Review <button aria-label="Remove Review">${ui('x')}</button></span><input id="e7-tags" value="dev" aria-label="Add a tag"></div><div class="ui-popover ui-menu" role="listbox" aria-label="Tag suggestions">${suggestion('Development', true)}${suggestion('Device support')}${suggestion('Dev tools')}</div></div>`, align: 'start' },
  'file-drop-zone': { html: `<div class="ui-col" style="width:min(390px,100%);gap:8px"><span class="ui-label">Add files</span><div class="e7-drop" role="group" aria-label="File drop zone">${ui('inbox')}<b>Drop files here</b><span class="ui-description">or browse from your computer</span><button class="ui-btn ui-btn--outline ui-btn--sm">Choose files</button></div></div>`, align: 'start' },
  'file-field': { html: `<div class="ui-col" style="width:min(340px,100%);gap:8px"><span class="ui-label">Source files</span><span class="ui-description">Choose PDF or text files</span><button class="ui-btn ui-btn--primary e7-file-button">Change files</button><div class="e7-file-row"><span>${ui('file')} brief.pdf <small>18.0 KB</small></span><button class="e7-remove">Remove</button></div></div>`, align: 'start' },
  stepper: { html: `<div class="ui-col" style="width:min(420px,100%);gap:10px"><span class="ui-label">Stepper</span><span class="ui-description">middle</span><ol class="e7-stepper" aria-label="Setup progress"><li class="is-complete"><span>1. Account details</span><small>Complete</small></li><li class="is-current" aria-current="step"><span>2. Preferences</span><small>Current</small></li><li><span>3. Review and finish</span><small>Upcoming</small></li></ol><div class="e7-stepper-actions"><button class="ui-btn ui-btn--outline">Back</button><button class="ui-btn">Next</button></div></div>`, align: 'start' },
  'reorderable-list': { html: `<div class="ui-col" style="width:min(360px,100%);gap:8px"><span class="ui-label">Layers</span><div class="ui-card e7-reorder-list" role="list" aria-label="Layers">${[['Header', 'Move up'], ['Hero image', 'Active, position 2 of 4'], ['Caption', 'Move down'], ['Footer', '']].map(([name, label], i) => `<div class="e7-reorder-row${i === 1 ? ' is-active' : ''}" role="listitem" aria-posinset="${i + 1}" aria-setsize="4" tabindex="${i === 1 ? '0' : '-1'}"><span class="e7-grip" aria-hidden="true">${ui('grip-vertical')}</span>${ui(i === 1 ? 'image' : 'layers')}<span>${name}</span><span class="ui-muted ui-small">${label}</span></div>`).join('')}</div><span class="ui-description">Use Alt + ↑ / ↓ to reorder the active row.</span></div>`, align: 'start' },
  'menu-bar': { html: `<div class="ui-col" style="gap:8px;width:min(420px,100%)"><span class="ui-label">Menu bar · open</span><div class="e7-menubar" role="menubar" aria-label="Application menu"><button role="menuitem" aria-haspopup="menu" aria-expanded="true" class="is-open"><small>(f)</small>File</button><button role="menuitem" aria-haspopup="menu"><small>(e)</small>Edit</button></div><div class="ui-popover ui-menu e7-menubar-menu" role="menu" aria-label="File menu"><div class="ui-menu__item is-active" role="menuitem">New</div><div class="ui-menu__item" role="menuitem" aria-disabled="true">Save<span class="ui-menu__shortcut">⌘S</span></div><div class="ui-menu__sep"></div><div class="ui-menu__item" role="menuitem">Recent${ui('chevron-right')}</div></div></div>`, align: 'start' },
}
